---
- name: "Install global packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.global }}"
    state: present

- name: "Install fedora tools packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.fedora.tools }}"
    state: present

- name: "Install fedora gaming packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.fedora.gaming }}"
    state: present

- name: "Install flatpak"
  community.general.flatpak:
    name: "{{ flatpak_list.fedora }}"
    state: present

- name: Add docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: "Install docker packages"
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present

- name: "Start service docker"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes