---
# vars file for base

packages_list:
  - vim
  - neovim
  - git
  - net-tools
  - steam
  - lutris
  - snapd
  - 0ad
  - 0ad-data

flatpak_list:
  - com.bitwarden.desktop
  - com.vscodium.codium
  - com.github.IsmaelMartinez.teams_for_linux
  - com.discordapp.Discord
  - io.github.hmlendea.geforcenow-electron
  - im.riot.Riot
  - com.mattjakeman.ExtensionManager