---
- name: "Install fedora tools packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.fedora.tools }}"
"{{ packages_list.fedora.gaming }}"
    state: present

- name: "Install fedora gaming packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.fedora.gaming }}"
    state: present