---
- name: "Install fedora tools packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.fedora.tools }}"
    state: present

- name: "Install fedora gaming packages"
  ansible.builtin.dnf:
    name: "{{ packages_list.fedora.gaming }}"
    state: present

- name: "Install flatpak"
  community.general.flatpak:
    name: "{{ flatpak_list.fedora }}"
    state: present