# Group
- name: Add user in group
  ansible.builtin.user:
    name: xataz
    shell: /bin/bash
    groups: wheel,lxd,docker
    append: yes

# ASDF
- name: Download Asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: /home/xataz/.asdf
    version: v0.13.1

- name: change ownership of an asdf directory
  ansible.builtin.file:
    path: /home/xataz/.asdf
    state: directory
    recurse: yes
    owner: xataz
    group: xataz

- name: Configure Asdf for bash
  ansible.builtin.lineinfile:
    path: /home/xataz/.bashrc
    line: '. "$HOME/.asdf/asdf.sh"'
    owner: xataz
    group: xataz

- name: Configure Asdf Completion for bash
  ansible.builtin.lineinfile:
    path: /home/xataz/.bashrc
    line: '. "$HOME/.asdf/completions/asdf.bash"'
    owner: xataz
    group: xataz
